version: 2.1

executors:
  ruby:
    resource_class: small
    docker:
      - image: cimg/ruby:2.6
        environment:
          BUNDLE_VERSION: "~> 2.1.4"
  ruby-with-redis:
    resource_class: small
    docker:
      - image: cimg/ruby:2.6
        environment:
          BUNDLE_VERSION: "~> 2.1.4"
      - image: redis:4-alpine
        command: redis-server

# yaml anchor filters
always_run: &always_run
  filters:
    branches:
      only: /.*/
    tags:
      only: /^v.*/
pr_only: &pr_only
  filters:
    branches:
      ignore: master
    tags:
      ignore: /.*/
version_tags_only: &version_tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

jobs:
  build:
    executor: ruby-with-redis
    steps:
      - checkout
      - run:
          name: Install Bundler specific version
          command: |
            gem install bundler --version "${BUNDLE_VERSION}" --force
      - run:
          name: Install Ruby Dependencies
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - run:
          name: Run Tests
          command: bundle exec rake ci:specs
      - store_test_results:
          name: Store test results
          path: tmp/test-results
      - run:
          name: Run StandardRB
          command: bundle exec standardrb
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle

workflows:
  main:
    jobs:
      - build:
          <<: *always_run
          context: sidekiq-enterprise
